$ANSIBLE_VAULT;1.1;AES256
63386464646566613538636165336338393761343836373830363838626363373164326133393462
6639623239346631623134303331343037623262623461650a623061633931613736306562643564
63643466336431623564396532323663366362396334663331656161646234343834383764383962
3330343732663734640a396531336564366666653839373965313038336436613465336562356239
35613636383830373038353939613639366633343561313436326464303161616436316266663632
34626236383039653839383934316132363335333631383661316235326334663265356136613037
64356234323539613866376561633637643035376531336638373534373261313263613461346564
35383239653938313433656236363230653139346439373930323265326333306231363636303162
31343831353066326262376330383636386235326434386137636432363132383663306336346236
32353136343332346364643966386234393265303736666562393735396431393865363463623336
30376461363833636633333261633663663361373137383433393436353966613430626631303964
62623361353736393561643163303433326162333566336135363236633465336134663066643165
36363664343839666537363230636334323865313438396466386466633236313333
