$ANSIBLE_VAULT;1.1;AES256
38323866356363396332393234636633633966623632383737626531323261343765333735616137
3364393136333136306465383261663364643730653939340a353163333862343466646561316439
34383064306334646538316639333939383431373561376231333566643330343266616664383738
6337363731663730620a316561376361383839306233636364303461316633663732646236663162
36383633323864343965353930666239383765326639303034353230316336646436363038393232
31613033373434633965316534613636326464383066363034323838643461396363373633643335
656633303362613738666365626339303561
